import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const appCss = readFileSync("public/css/app.css", "utf8");
const tokenCss = readFileSync("public/css/tokens.css", "utf8");
const indexHtml = readFileSync("public/index.html", "utf8");
const appJs = readFileSync("public/js/app.js", "utf8");
const serviceWorker = readFileSync("public/service-worker.js", "utf8");

test("desktop dashboard uses the full width with a logo-triggered app menu", () => {
  assert.match(appCss, /\.app-shell\s*{[\s\S]*?align-content:\s*start;/);
  assert.match(appCss, /\.app-shell\s*{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) minmax\(360px, 500px\);/);
  assert.match(appCss, /\.top-dock\s*{[\s\S]*?grid-column:\s*1 \/ 3;[\s\S]*?grid-template-columns:\s*72px minmax\(220px, 1fr\) minmax\(120px, \.62fr\);/);
  assert.match(indexHtml, /<\/section>\s*<section class="quote-card glass-panel" aria-label="Цитаты дня">[\s\S]*?<section class="dashboard-grid">/);
  assert.doesNotMatch(indexHtml, /id="quotePrev"|id="quoteNext"/);
  assert.match(appCss, /\.quote-card\s*{[\s\S]*?grid-column:\s*1 \/ 3;[\s\S]*?grid-row:\s*2;[\s\S]*?grid-template-columns:\s*auto minmax\(0, 1fr\);/);
  assert.match(appCss, /\.quote-marquee\s*{[\s\S]*?overflow:\s*hidden;/);
  assert.match(appCss, /\.quote-card p\s*{[\s\S]*?animation:\s*quote-marquee 26s linear infinite;/);
  assert.match(appCss, /\.quote-card p::after\s*{[\s\S]*?content:\s*attr\(data-quote-copy\);/);
  assert.match(appCss, /@keyframes quote-marquee/);
  assert.match(appJs, /quoteText\.dataset\.quoteCopy = text;/);
  assert.match(indexHtml, /id="quotesModal"/);
  assert.match(indexHtml, /id="dailyQuotesList"/);
  assert.match(indexHtml, /id="quoteCategoryOptions"/);
  assert.match(indexHtml, /data-open-modal="quotes"/);
  assert.match(appJs, /quotes:\s*document\.querySelector\("#quotesModal"\)/);
  assert.match(appJs, /document\.querySelector\("\.quote-card"\)\?\.addEventListener\("click"/);
  assert.match(appJs, /scheduleSync\.getTodayQuotes/);
  assert.match(appJs, /scheduleStorage\.loadDailyQuotesCache/);
  assert.match(appJs, /scheduleStorage\.saveDailyQuotesCache/);
  assert.match(appCss, /\.date-card,\s*\.quote-card\s*{[\s\S]*?height:\s*var\(--top-dock-height\);[\s\S]*?box-sizing:\s*border-box;/);
  assert.match(appCss, /\.add-wrap\s*{[\s\S]*?height:\s*var\(--top-dock-height\);/);
  assert.match(appCss, /\.add-button\s*{[\s\S]*?height:\s*var\(--top-dock-height\);/);
  assert.match(indexHtml, /id="brandMenuButton"[\s\S]*?aria-controls="appMenu"/);
  assert.match(indexHtml, /<aside class="sidebar" id="appMenu"[\s\S]*?hidden>/);
  assert.match(appCss, /\.brand-mark--topbar\s*{[\s\S]*?animation:\s*brand-breathe 4\.2s ease-in-out infinite;/);
  assert.match(appCss, /@keyframes brand-breathe/);
  assert.match(appCss, /transform:\s*scale\(1\.075\)/);
  assert.match(appCss, /0 0 0 10px rgba\(249, 115, 22, \.26\)/);
  assert.match(appCss, /0 22px 56px rgba\(249, 115, 22, \.42\)/);
  assert.doesNotMatch(appCss, /brand-glint|brand-shimmer|linear-gradient\(112deg/);
  assert.match(appCss, /\.app-shell \.sidebar\s*{[\s\S]*?position:\s*fixed\s*!important;[\s\S]*?width:\s*min\(304px, calc\(100vw - 28px\)\)\s*!important;/);
  assert.match(appCss, /\.app-shell \.sidebar__nav\s*{[\s\S]*?grid-template-columns:\s*1fr\s*!important;/);
  assert.match(appJs, /function openAppMenu\(\)/);
  assert.match(appJs, /function closeAppMenu\(\)/);
  assert.match(appCss, /\.main-stack\s*{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/);
  assert.match(appCss, /\.calendar-card\s*{[\s\S]*?grid-column:\s*1;[\s\S]*?width:\s*100%;/);
  assert.match(appCss, /\.labels-row\s*{[\s\S]*?grid-column:\s*1;[\s\S]*?width:\s*100%;/);
  assert.match(appCss, /\.interesting\s*{[\s\S]*?grid-column:\s*1;[\s\S]*?width:\s*100%;/);
  assert.match(appCss, /\.side-stack\s*{[\s\S]*?grid-row:\s*3;/);
  assert.match(appCss, /\.side-stack\s*{[\s\S]*?grid-template-rows:\s*auto minmax\(220px, 1fr\);/);
  assert.match(appCss, /\.tasks-card\s*{[\s\S]*?min-height:\s*220px;/);
  assert.match(indexHtml, /<div class="main-stack">[\s\S]*?<section class="labels-row[\s\S]*?<section class="interesting glass-panel">[\s\S]*?<\/div>\s*<aside class="side-stack">/);
  assert.match(indexHtml, /<section class="interesting glass-panel interesting--legacy" hidden>/);
  assert.doesNotMatch(appCss, /max-height:\s*calc\(100vh - 124px\)/);
});

test("service worker cache is bumped after desktop layout CSS changes", () => {
  assert.match(serviceWorker, /focus-pwa-v119/);
});

test("main calendar exposes independent semantic date statuses", () => {
  assert.match(tokenCss, /--calendar-today:\s*#3f6ff4;/);
  assert.match(tokenCss, /--calendar-non-working-day:\s*#d96b5f;/);
  assert.match(tokenCss, /--calendar-secular-holiday:\s*#f97316;/);
  assert.match(tokenCss, /--calendar-religious-holiday:\s*#5f9073;/);
  assert.match(tokenCss, /--calendar-working-weekend:\s*#4c433a;/);
  assert.match(appJs, /function getCalendarDateStatus/);
  assert.match(appJs, /function getCalendarStatusBackground/);
  assert.match(appJs, /var\(--calendar-today\), transparent 48%/);
  assert.match(appJs, /var\(--calendar-non-working-day\), transparent 56%/);
  assert.match(appJs, /var\(--calendar-secular-holiday\), transparent 58%/);
  assert.match(appJs, /var\(--calendar-religious-holiday\), transparent 58%/);
  assert.match(appJs, /var\(--calendar-working-weekend\), transparent 72%/);
  assert.match(appJs, /function getHolidayEventTypes/);
  assert.match(appJs, /getHolidayEventTypes\(event\)\.has\("working_weekend"\)/);
  assert.match(appJs, /event\.isOfficialNonWorkingDay === true/);
  assert.match(appJs, /"public_holiday",\s*"commemorative_date",\s*"professional_holiday"/);
  assert.match(appJs, /getHolidayEventTypes\(event\)\.has\("religious_holiday"\)/);
  assert.match(appJs, /getCalendarDateAriaLabel/);
  assert.match(appJs, /day-cell--non-working/);
  assert.match(appJs, /day-cell--secular-holiday/);
  assert.match(appJs, /day-cell--religious-holiday/);
  assert.match(appJs, /--calendar-status-bg:\$\{escapeHtml\(statusBackground\)\}/);
  assert.match(appJs, /linear-gradient\(135deg, \$\{stops\.join\(", "\)\}\)/);
  assert.doesNotMatch(appJs, /calendar-status-markers|calendar-status-dot--secular|calendar-status-dot--religious|calendar-status-dot--working/);
  assert.doesNotMatch(appJs, /getHolidayEventsForDate\(date\)\.forEach\(event => \{\s*markers\.push\(event\.color\);/);
  assert.match(appCss, /\.day-cell\s*{[\s\S]*?--calendar-cell-base-bg:[\s\S]*?background:\s*var\(--calendar-status-bg, transparent\), var\(--calendar-cell-base-bg\);/);
  assert.match(appCss, /\.day-cell:hover\s*{[\s\S]*?background:\s*var\(--calendar-status-bg, transparent\), var\(--calendar-cell-hover-bg\);/);
  assert.match(appCss, /\.day-cell__num\s*{[\s\S]*?display:\s*block;/);
  assert.doesNotMatch(appCss, /\.day-cell--current \.day-cell__num|\.calendar-status-markers|\.calendar-status-dot/);
});

test("warm glass summary keeps text contrast above the seasonal background", () => {
  assert.match(tokenCss, /--text:\s*#1f1a16;/);
  assert.match(tokenCss, /--text-soft:\s*#342d27;/);
  assert.match(tokenCss, /--text-muted:\s*#4c433a;/);
  assert.match(tokenCss, /--glass-1:\s*rgba\(255,\s*252,\s*244,\s*\.34\);/);
  assert.match(tokenCss, /--glass-strong:\s*rgba\(255,\s*252,\s*244,\s*\.64\);/);
  assert.match(appCss, /\.summary-card,\s*\.tasks-card\s*{[\s\S]*?rgba\(255,\s*252,\s*244,\s*\.52\)[\s\S]*?border-color:\s*rgba\(255,\s*255,\s*255,\s*\.66\);/);
  assert.match(appCss, /\.summary-title\s*{[\s\S]*?color:\s*color-mix\(in srgb,\s*var\(--summary-color,\s*var\(--text\)\),\s*#1f1a16 42%\);/);
  assert.match(appCss, /\.day-card-event\s*{[\s\S]*?--event-readable-color:\s*color-mix\(in srgb,\s*var\(--event-color\),\s*#1f1a16 42%\);[\s\S]*?border:\s*1px solid rgba\(255,\s*255,\s*255,\s*\.66\);/);
  assert.match(appCss, /\.day-card-event strong\s*{[\s\S]*?color:\s*var\(--event-readable-color\);/);
  assert.match(appCss, /\.day-card-event small\s*{[\s\S]*?color:\s*#4c433a;[\s\S]*?font-weight:\s*720;/);
  assert.match(appCss, /\.summary-time\s*{[\s\S]*?color:\s*#332c27;/);
  assert.match(appCss, /\.day-card-event__time\s*{[\s\S]*?color:\s*#332c27;/);
  assert.match(appCss, /\.summary-item\s*{[\s\S]*?border:\s*1px solid rgba\(255,\s*255,\s*255,\s*\.62\);[\s\S]*?rgba\(255,\s*252,\s*244,\s*\.54\)/);
  assert.match(readFileSync("public/js/app.js", "utf8"), /class="summary-title" style="--summary-color:\$\{item\.color\}"/);
});
